### ISSUE TITLE
Can not 

### ISSUE THREAD

**Issue by pradeepta** [chenxwh/cog-themed-diffusion#3]
Hello, I can not download weights using instructions (I am trying to fork off your repo to input a image url instead of a file) to host a version on replicate.

`Running 'script/download-weights' in Docker with the current directory mounted as a volume...
Downloading (…)ain/model_index.json: 100%|████████████████████████████████████████████████████████████████████████████████| 616/616 [00:00<00:00, 468kB/s]
Traceback (most recent call last):
  File "/src/script/download-weights", line 16, in <module>
    pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 592, in from_pretrained
    config_dict = cls.load_config(
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 380, in load_config
    config_dict = cls._dict_from_json_file(config_file)
  File "/root/.pyenv/versions/3.10.10/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 479, in _dict_from_json_file
    with open(json_file, "r", encoding="utf-8") as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'diffusers-cache/models--timbrooks--instruct-pix2pix/snapshots/93224554bd65f19b6f0c99cbcce3a4ac59bb6382/model_index.json'
ⅹ exit status 1
root@ubuntu-22-04-cuda-12-0-docker-1a100-22v-fin1:/cog-themed-diffusion# cd diffusers-cache/models--timbrooks--instruct-pix2pix/
`

**Comment by pradeepta** [comment]
This is what the cache directory looks like 
`root@ubuntu-22-04-cuda-12-0-docker-1a100-22v-fin1:/cog-themed-diffusion/diffusers-cache# find .
.
./models--timbrooks--instruct-pix2pix
./models--timbrooks--instruct-pix2pix/refs
./models--timbrooks--instruct-pix2pix/refs/main
./models--timbrooks--instruct-pix2pix/snapshots
./models--timbrooks--instruct-pix2pix/snapshots/93224554bd65f19b6f0c99cbcce3a4ac59bb6382
./models--timbrooks--instruct-pix2pix/snapshots/93224554bd65f19b6f0c99cbcce3a4ac59bb6382/model_index.json
./models--timbrooks--instruct-pix2pix/blobs
./models--timbrooks--instruct-pix2pix/blobs/b1b17da0fdfb6cee5f986f8a70572b1f63f1a45e
`

**Comment by chenxwh** [comment]
it seems to be a huggingface hub change issue, in the main repo I have temp fix before maybe HF fix the `cache_dir`. See thread here https://github.com/replicate/cog-stable-diffusion/issues/74#issuecomment-1462616896, you can adapt saving and loading model accordingly maybe for now
